/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

     "github.com/joho/godotenv"
	sw "github.com/guildmember145/khipu_api_go/go"
)

func main() {
	// Cargar variables de entorno desde el archivo .env
	// Equivalente a load_dotenv() en run.py
	err := godotenv.Load()
	if err != nil {
		log.Println("Advertencia: No se pudo cargar el archivo .env. Se usarán variables de entorno del sistema.")
	}

	routes := sw.ApiHandleFunctions{DefaultAPI: sw.DefaultAPI{}}

	log.Printf("Servidor iniciado en el puerto 8080")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
