/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MerchantGetPaymentMethods struct {

	// Arreglo con métodos de pago disponibles.
	PaymentMethods []MerchantGetPaymentMethodsPaymentMethodsInner `json:"paymentMethods"`
}
