/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BankGetBanks struct {

	// Arreglo con listado de bancos.
	Banks []BankGetBanksBanksInner `json:"banks"`
}
