/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// PaymentPostPayment - Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
type PaymentPostPayment struct {

	// El monto del cobro. Sin separador de miles y usando '.' como separador de decimales. Hasta 4 lugares decimales, dependiendo de la moneda.
	Amount float64 `json:"amount"`

	// El código de moneda en formato ISO-4217.
	Currency string `json:"currency"`

	// Motivo.
	Subject string `json:"subject"`

	// Identificador propio de la transacción. Ej: número de factura u orden de compra.
	TransactionId string `json:"transaction_id,omitempty"`

	// Parámetro para enviar información personalizada de la transacción. Ej: documento XML con el detalle del carro de compra.
	Custom string `json:"custom,omitempty"`

	// Descripción del cobro.
	Body string `json:"body,omitempty"`

	// Identificador del banco para usar en el pago.
	BankId string `json:"bank_id,omitempty"`

	// La dirección URL a donde enviar al cliente mientras el pago está siendo verificado.
	ReturnUrl string `json:"return_url,omitempty"`

	// La dirección URL a donde enviar al cliente si decide no hacer hacer la transacción.
	CancelUrl string `json:"cancel_url,omitempty"`

	// Una dirección URL de una foto de tu producto o servicio.
	PictureUrl string `json:"picture_url,omitempty"`

	// La dirección del web-service que utilizará khipu para notificar cuando el pago esté conciliado.
	NotifyUrl string `json:"notify_url,omitempty"`

	// La dirección URL del archivo PDF con el contrato a firmar mediante este pago. El cobrador debe estar habilitado para este servicio y el campo `fixed_payer_personal_identifier` es obligatorio.
	ContractUrl string `json:"contract_url,omitempty"`

	// Versión de la API de notificaciones para recibir avisos por web-service.
	NotifyApiVersion string `json:"notify_api_version,omitempty"`

	// Fecha máxima para ejecutar el pago (en formato ISO-8601). El cliente podrá realizar varios intentos de pago hasta dicha fecha. Cada intento tiene un plazo individual de 3 horas para su ejecución.
	ExpiresDate time.Time `json:"expires_date,omitempty"`

	// Si es `true`, se enviará una solicitud de cobro al correo especificado en `payer_email`.
	SendEmail bool `json:"send_email,omitempty"`

	// Nombre del pagador. Es obligatorio cuando `send_email` es `true`.
	PayerName string `json:"payer_name,omitempty"`

	// Correo del pagador. Es obligatorio cuando `send_email` es `true`.
	PayerEmail string `json:"payer_email,omitempty"`

	// Si es `true`, se enviarán recordatorios de cobro.
	SendReminders bool `json:"send_reminders,omitempty"`

	// Correo electrónico del responsable de este cobro, debe corresponder a un usuario Khipu con permisos para cobrar usando esta cuenta de cobro.
	ResponsibleUserEmail string `json:"responsible_user_email,omitempty"`

	// Identificador personal. Si se especifica, solo podrá ser pagado usando ese identificador.
	FixedPayerPersonalIdentifier string `json:"fixed_payer_personal_identifier,omitempty"`

	// Comisión para el integrador. Sólo es válido si la cuenta de cobro tiene una cuenta de integrador asociada.
	IntegratorFee string `json:"integrator_fee,omitempty"`

	// Para cuentas de cobro con más cuenta propia. Permite elegir la cuenta donde debe ocurrir la transferencia.
	CollectAccountUuid string `json:"collect_account_uuid,omitempty"`

	// Fecha de rendición del cobro. Es también la fecha final para poder reembolsar el cobro. Formato ISO-8601.
	ConfirmTimeoutDate time.Time `json:"confirm_timeout_date,omitempty"`

	// El cobro sólo se podrá pagar utilizando el medio de pago especificado. Los posibles valores para este campo se encuentran en el campo `id` de la respuesta del endpoint `/api/3.0/merchants/paymentMethods`.
	MandatoryPaymentMethod string `json:"mandatory_payment_method,omitempty"`

	// Nombre del comercio final para quien un proveedor de servicios de pago procesa un pago. Requerido para transacciones de clientes PSP; no aplicable para otros. En caso de tratarse de un PSP de PSP, estos deben ingresarse separados por '->'.
	PspClientMerchantName string `json:"psp_client_merchant_name,omitempty"`
}
