/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PaymentPostPayment2 - Crea un pago en Khipu y obtiene las URLs para redirección al usuario para que complete el pago.
type PaymentPostPayment2 struct {

	// Identificador único del pago, es una cadena alfanumérica de 12 caracteres. Como este identificador es único, se puede usar, por ejemplo, para evitar procesar una notificación repetida. (Khipu espera un código 200 al notificar un pago, si esto no ocurre se reintenta hasta por dos días).
	PaymentId string `json:"payment_id"`

	// URL principal del pago, si el usuario no ha elegido previamente un método de pago se le muestran las opciones.
	PaymentUrl string `json:"payment_url"`

	// URL de pago simplificado.
	SimplifiedTransferUrl string `json:"simplified_transfer_url"`

	// URL de pago normal.
	TransferUrl string `json:"transfer_url"`

	// URL para invocar el pago desde un dispositivo móvil usando la APP de Khipu.
	AppUrl string `json:"app_url"`

	// Es `true` si el pago ya cuenta con todos los datos necesarios para abrir directamente la aplicación de pagos Khipu.
	ReadyForTerminal bool `json:"ready_for_terminal"`
}
