/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ReceiverPostReceiver - Crear una nueva cuenta de cobro asociada a un integrador. Necesita datos de la cuenta de usuario asociada, datos de facturación y datos de contacto.
type ReceiverPostReceiver struct {

	// Nombre de pila del administrador de la cuenta de cobro a crear.
	AdminFirstName string `json:"admin_first_name"`

	// Apellido del administrador de la cuenta de cobro a crear.
	AdminLastName string `json:"admin_last_name"`

	// Correo electrónico del administrador de la cuenta de cobro a crear.
	AdminEmail string `json:"admin_email"`

	// Código alfanumérico de dos caracteres ISO 3166-1 del país de la cuenta de cobro a crear.
	CountryCode string `json:"country_code"`

	// Identificador tributario del cobrador asociado a la cuenta de cobro a crear.
	BusinessIdentifier string `json:"business_identifier"`

	// Categoría tributaria o rubro tributario del cobrador asociado a la cuenta de cobro a crear.
	BusinessCategory string `json:"business_category"`

	// Nombre tributario del cobrador asociado a la cuenta de cobro a crear.
	BusinessName string `json:"business_name"`

	// Teléfono del cobrador asociado a la cuenta de cobro a crear.
	BusinessPhone string `json:"business_phone"`

	// Dirección del cobrador de la cuenta de cobro a crear.
	BusinessAddressLine1 string `json:"business_address_line_1"`

	// Segunda línea de la dirección del cobrador de la cuenta de cobro a crear.
	BusinessAddressLine2 string `json:"business_address_line_2"`

	// Tercera línea de la dirección del cobrador de la cuenta de cobro a crear.
	BusinessAddressLine3 string `json:"business_address_line_3"`

	// Nombre del contacto del cobrador.
	ContactFullName string `json:"contact_full_name"`

	// Cargo del contacto del cobrador.
	ContactJobTitle string `json:"contact_job_title"`

	// Correo electrónico del contacto del cobrador.
	ContactEmail string `json:"contact_email"`

	// Teléfono del contacto del cobrador.
	ContactPhone string `json:"contact_phone"`

	// Identificador del banco.
	BankAccountBankId string `json:"bank_account_bank_id,omitempty"`

	// Tipo de cuenta. Es obligatorio si se utiliza el modelo alternativo de integrador de confianza.
	BankAccountType string `json:"bank_account_type,omitempty"`

	// Identificador personal del dueño de la cuenta de banco.
	BankAccountIdentifier string `json:"bank_account_identifier,omitempty"`

	// Nombre de la cuenta de banco.
	BankAccountName string `json:"bank_account_name,omitempty"`

	// Número de la cuenta en el banco.
	BankAccountNumber string `json:"bank_account_number,omitempty"`

	// URL por omisión para el webservice donde se notificará el pago.
	NotifyUrl string `json:"notify_url,omitempty"`

	// URL para el webservice donde se notificará la rendición.
	RenditionUrl string `json:"rendition_url,omitempty"`
}
