/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Success - Objeto para respuestas exitosas de la API.
type Success struct {

	// Mensaje a desplegar al usuario.
	Message string `json:"message"`
}
