/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MerchantGetPaymentMethodsPaymentMethodsInner - Método de pago.
type MerchantGetPaymentMethodsPaymentMethodsInner struct {

	// Identificador del medio de pago.
	Id string `json:"id"`

	// Nombre del medio de pago.
	Name string `json:"name"`

	// URL del logo sugerido para mostrar.
	LogoUrl string `json:"logo_url"`
}
