/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ReceiverPostReceiver2 - Objeto para respuesta de creación de cuenta de cobro.
type ReceiverPostReceiver2 struct {

	// Identificador único de la cuenta de cobro.
	ReceiverId string `json:"receiver_id"`

	// Llave secreta de la cuenta de cobro, se usa para firmar todas las peticiones.
	Secret string `json:"secret"`
}
