/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PredictGetPredict - Predicción acerca del resultado de un pago, si podrá o no funcionar. Información adicional como máximo posible de transferir a un nuevo destinatario.
type PredictGetPredict struct {

	// El resultado de la predicción.
	Result string `json:"result"`

	// El monto máximo posible para transferir.
	MaxAmount float64 `json:"max_amount"`

	// Fecha de término para la restricción de monto en formato ISO-8601
	CoolDownDate string `json:"cool_down_date"`

	// Monto máximo para transferir a un nuevo destinatario.
	NewDestinataryMaxAmount float64 `json:"new_destinatary_max_amount"`
}
