/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BankGetBanksBanksInner - Datos de banco.
type BankGetBanksBanksInner struct {

	// Identificador del banco.
	BankId string `json:"bank_id"`

	// Nombre del banco.
	Name string `json:"name"`

	// Mensaje con particularidades del banco.
	Message string `json:"message"`

	// Monto mínimo que acepta el banco en un pago.
	MinAmount float64 `json:"min_amount"`

	// Tipo de banco.
	Type string `json:"type"`

	// Identificador del banco padre (si un banco tiene banca personas y empresas, el primero será el padre del segundo).
	Parent string `json:"parent"`

	// URL del logo del banco.
	LogoUrl string `json:"logo_url,omitempty"`
}
