/*
 * API Pagos Instantáneos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// PaymentGetPayment - Información completa del pago. Datos con los que fue creado y el estado actual del pago.
type PaymentGetPayment struct {

	// Identificador único del pago, es una cadena alfanumérica de 12 caracteres. Como este identificador es único, se puede usar, por ejemplo, para evitar procesar una notificación repetida. (Khipu espera un código 200 al notificar un pago, si esto no ocurre se reintenta hasta por dos días).
	PaymentId string `json:"payment_id"`

	// URL principal del pago, si el usuario no ha elegido previamente un método de pago se le muestran las opciones.
	PaymentUrl string `json:"payment_url"`

	// URL de pago simplificado.
	SimplifiedTransferUrl string `json:"simplified_transfer_url"`

	// URL de pago normal.
	TransferUrl string `json:"transfer_url"`

	// URL para invocar el pago desde un dispositivo móvil usando la APP de Khipu.
	AppUrl string `json:"app_url"`

	// Es `true` si el pago ya cuenta con todos los datos necesarios para abrir directamente la aplicación de pagos Khipu.
	ReadyForTerminal bool `json:"ready_for_terminal"`

	// Cadena de caracteres alfanuméricos que identifican unicamente al pago, es el identificador que el servidor de Khipu enviará al servidor del comercio cuando notifique que un pago está conciliado.
	NotificationToken string `json:"notification_token"`

	// Identificador único de una cuenta de cobro.
	ReceiverId int64 `json:"receiver_id"`

	// Fecha y hora de conciliación del pago. Formato ISO-8601.
	ConciliationDate time.Time `json:"conciliation_date"`

	// Motivo del pago.
	Subject string `json:"subject"`

	// El monto del cobro.
	Amount float64 `json:"amount"`

	// El código de moneda en formato ISO-4217.
	Currency string `json:"currency"`

	// Estado del pago, puede ser `pending` (el pagador aún no comienza a pagar), `verifying` (se está verificando el pago) o `done`, cuando el pago ya está confirmado.
	Status string `json:"status"`

	// Detalle del estado del pago: `pending` (el pagador aún no comienza a pagar), `normal` (el pago fue verificado y fue cancelado por algún medio de pago estándar), `marked-paid-by-receiver` (el cobrador marcó el cobro como pagado por otro medio), `rejected-by-payer` (el pagador declaró que no pagará), `marked-as-abuse` (el pagador declaró que no pagará y que el cobro fue no solicitado), y `reversed` (el pago fue anulado por el comercio, el dinero fue devuelto al pagador).
	StatusDetail string `json:"status_detail"`

	// Detalle del cobro.
	Body string `json:"body"`

	// URL con imagen del cobro.
	PictureUrl string `json:"picture_url"`

	// URL del comprobante de pago.
	ReceiptUrl string `json:"receipt_url"`

	// URL donde se redirige al pagador luego que termina el pago.
	ReturnUrl string `json:"return_url"`

	// URL donde se redirige al pagador luego de que desiste hacer el pago.
	CancelUrl string `json:"cancel_url"`

	// URL del webservice donde se notificará el pago.
	NotifyUrl string `json:"notify_url"`

	// Versión de la API de notificación.
	NotifyApiVersion string `json:"notify_api_version"`

	// Fecha máxima para ejecutar el pago (en formato ISO-8601). El cliente podrá realizar varios intentos de pago hasta dicha fecha. Cada intento tiene un plazo individual de 3 horas para su ejecución.
	ExpiresDate time.Time `json:"expires_date"`

	// Arreglo de URLs de archivos adjuntos al pago.
	AttachmentUrls []string `json:"attachment_urls"`

	// Nombre del banco seleccionado por el pagador.
	Bank string `json:"bank"`

	// Identificador del banco seleccionado por el pagador.
	BankId string `json:"bank_id"`

	// Nombre del pagador.
	PayerName string `json:"payer_name"`

	// Correo electrónico del pagador.
	PayerEmail string `json:"payer_email"`

	// Identificador personal del pagador.
	PersonalIdentifier string `json:"personal_identifier"`

	// Número de cuenta bancaria del pagador.
	BankAccountNumber string `json:"bank_account_number"`

	// Es `true` si la conciliación del pago fue hecha luego de la fecha de expiración.
	OutOfDateConciliation bool `json:"out_of_date_conciliation"`

	// Identificador del pago asignado por el cobrador.
	TransactionId string `json:"transaction_id"`

	// Campo genérico que asigna el cobrador al momento de hacer el pago.
	Custom string `json:"custom"`

	// Correo electrónico de la persona responsable del pago.
	ResponsibleUserEmail string `json:"responsible_user_email"`

	// Es `true` cuando este es un cobro por correo electrónico y Khipu enviará recordatorios.
	SendReminders bool `json:"send_reminders"`

	// Es `true` cuando Khipu enviará el cobro por correo electrónico.
	SendEmail bool `json:"send_email"`

	// Método de pago usado por el pagador, puede ser `regular_transfer` (transferencia normal) o `simplified_transfer` (transferencia simplificada).
	PaymentMethod string `json:"payment_method"`

	// Origen de fondos usado por el pagador, puede ser `debit` para pago con débito, `prepaid` para pago con prepago, `credit` para pago con crédito, o vacío en el caso de que se haya pagado mediante transferencia bancaria.
	FundsSource string `json:"funds_source"`

	// Monto a descontar del valor pagado.
	Discount float64 `json:"discount,omitempty"`

	// Ignorar este campo.
	ThirdPartyAuthorizationDetails string `json:"third_party_authorization_details,omitempty"`
}
